language: generic
sudo: required
service:
  - docker

before_install:
  docker build -f ./client/Dockerfile.dev -t rajuuu1992/multi-container-docker-client ./client

script:
  - docker run -e CI=true rajuuu1992/multi-container-docker-client npm run test 

after_success:
  - docker build -t rajuuu1992/multi-client ./client
  - docker build -t rajuuu1992/multi-server ./server
  - docker build -t rajuuu1992/multi-worker ./workder
  - docker build -t rajuuu1992/multi-nginx ./nginx
  
  # docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
  # push to docker images  
  - docker push rajuuu1992/multi-client
  - docker push rajuuu1992/multi-server
  - docker push rajuuu1992/multi-worker
  - docker push rajuuu1992/multi-nginx
